# testing that PRF in util is (relatively) indistinguishable from random (using random package)
from src import util
import tests.testFunctions as tf


def test(tests, kLength, xLength):
    meanPRF = 0
    meanRand = 0
    rangePRF = 0
    rangeRand = 0

    numEvensRand = 0
    numEvensPRF = 0
    numOddsRand = 0
    numOddsPRF = 0
    for i in range(1, tests+1):
        # random array of length kLength
        randArr = tf.genRandomIntArray(xLength)
        e, o = tf.countEvensOdds(randArr)
        numEvensRand += e
        numOddsRand += o
        meanRand = tf.runningAvg(tf.getAvg(randArr), i, meanRand)
        rangeRand = tf.runningAvg(tf.getRange(randArr), i, rangeRand)

        # array of length kLength generated by prf(k, x)
        k = tf.genRandomIntArray(kLength)
        x = tf.genRandomIntArray(xLength)
        prfArr = util.PRF(k, x)
        e, o = tf.countEvensOdds(prfArr)
        numEvensPRF += e
        numOddsPRF += o
        meanPRF = tf.runningAvg(tf.getAvg(prfArr), i, meanPRF)
        rangePRF = tf.runningAvg(tf.getRange(prfArr), i, rangePRF)

    print("mean of PRF generated array: \t\t\t\t\t" + str(meanPRF))
    print("mean of randomly generated array: \t\t\t\t" + str(meanRand))
    print("avg. range of PRF generated array: \t\t\t\t" + str(rangePRF))
    print("avg. range of randomly generated array: \t\t\t" + str(rangeRand))
    print(
        f"comparison of evens to odds in PRF generated array: \t\t {numEvensPRF/tests:.3f}% : {numOddsPRF/tests:.3f}%")
    print(
        f"comparison of evens to odds in randomly generated array: \t {numEvensRand/tests:.3f}% : {numOddsRand/tests:.3f}%")


if __name__ == '__main__':
    test(50000, 50, 100)

"""
results = 

mean of PRF generated array:                                    127.53465200000034
mean of randomly generated array:                               127.5147024000001
avg. range of PRF generated array:                              250.84222000000025
avg. range of randomly generated array:                         250.87340000000006
comparison of evens to odds in PRF generated array:              49.972% : 50.028%
comparison of evens to odds in randomly generated array:         49.968% : 50.032%

Summary results are very similar for both randomly generated array using random package (tested PRG) and 
my own prf (non-tested) and look indistinuishable (though range and mean of randomly generated is slightly higher). 
Because no PRF can be proven (non-conditionally) secure, this seems like a sufficient test of reliability for the 
randomness we can get.
"""
