# testing that PRG in util is (relatively) indistinguishable from random (using random package)
from src import util
import tests.testFunctions as tf

def test(tests, arrLength):
    meanPRG = 0
    meanRand = 0
    rangePRG = 0
    rangeRand = 0

    numEvensRand = 0 
    numEvensPRG = 0 
    numOddsRand = 0 
    numOddsPRG = 0 
    for i in range(1, tests+1):
        # random array of length arrLength
        randArr = tf.genRandomIntArray(arrLength)
        e, o = tf.countEvensOdds(randArr)
        numEvensRand += e 
        numOddsRand += o
        meanRand = tf.runningAvg(tf.getAvg(randArr), i, meanRand)
        rangeRand = tf.runningAvg(tf.getRange(randArr), i, rangeRand)

        # array of length arrLength generated by prg in util
        prgArr = util.PRG(tf.genRandomIntArray(arrLength//2))
        e, o = tf.countEvensOdds(prgArr)
        numEvensPRG += e 
        numOddsPRG += o
        meanPRG = tf.runningAvg(tf.getAvg(prgArr), i, meanPRG)
        rangePRG = tf.runningAvg(tf.getRange(prgArr), i, rangePRG)

    print("mean of PRG generated array: \t\t\t\t\t" + str(meanPRG))
    print("mean of randomly generated array: \t\t\t\t" + str(meanRand))
    print("avg. range of PRG generated array: \t\t\t\t" + str(rangePRG))
    print("avg. range of randomly generated array: \t\t\t" + str(rangeRand))
    print(f"comparison of evens to odds in PRG generated array: \t\t {numEvensPRG/tests:.3f}% : {numOddsPRG/tests:.3f}%")
    print(f"comparison of evens to odds in randomly generated array: \t {numEvensRand/tests:.3f}% : {numOddsRand/tests:.3f}%")



if __name__ == '__main__':
    test(50000, 100)

"""
results = 

mean of PRG generated array:                                    127.50131460000023
mean of randomly generated array:                               127.49157339999991
avg. range of PRG generated array:                              250.72304000000028
avg. range of randomly generated array:                         250.86370000000005
comparison of evens to odds in PRG generated array:              49.989% : 50.011%
comparison of evens to odds in randomly generated array:         49.963% : 50.037%

Summary results are very similar for both randomly generated array using random package (tested PRG) and 
my own prg (non-tested) and look indistinuishable. 
Because no PRG can be proven secure, this seems like a sufficient test of reliability for the randomness 
we can get.
"""
